MvcPhoto2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcPhoto2.Models;

namespace MvcPhoto2.Controllers
{ 
    public class UserController : Controller
    {
        private Photo2Entities1 db = new Photo2Entities1();

        //
        // GET: /User/
        private List<SelectListItem> role_list = new
              List<SelectListItem> {
				                     	new SelectListItem {Text = "Admin", Value = "Admin"},
				                     	new SelectListItem {Text = "Photographer", Value = "Photographer"},
				                     	
				                     };
        [Authorize(Roles = "Admin")]
        public ViewResult Index()
        {
            return View(db.Authentications.ToList());
        }

        //
        // GET: /User/Details/5
         [Authorize(Roles = "Admin")]
        public ViewResult Details(string id)
        {
            Authentication authentication = db.Authentications.Find(id);
            return View(authentication);
        }

        //
        // GET: /User/Create
         [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.selectList = role_list;
            return View();
        } 

        //
        // POST: /User/Create

        //NOT WORKING ON TYPO???????
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult CreateUser(Authentication authentication)
        {
            if (ModelState.IsValid)
            {
                db.Authentications.Add(authentication);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(authentication);
        }
        
        //
        // GET: /User/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            ViewBag.selectList = role_list;
            Authentication authentication = db.Authentications.Find(id);
            return View(authentication);
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        public ActionResult Edit(Authentication authentication)
        {
            if (ModelState.IsValid)
            {
                db.Entry(authentication).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(authentication);
        }

        //
        // GET: /User/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            Authentication authentication = db.Authentications.Find(id);
            return View(authentication);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {            
            Authentication authentication = db.Authentications.Find(id);
            db.Authentications.Remove(authentication);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles= "Photographer")]
        public string GetNetId()
        {
            Authentication authentication = db.Authentications.Find(User.Identity.Name);
            //string Name = User.Identity.Name;
            //string Name = Byu.Utilities.LDAP.Lookup.getDetails(User.Identity.Name).FullName;
           
            string name = authentication.Name;
            
            return name;
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcPhoto2/Controllers/emailCartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcPhoto2.Models;
using System.Net.Mail;


namespace MvcPhoto2.Controllers
{ 
    public class emailCartController : Controller
    {
        private Photo2repo repo = new Photo2repo();
        //
        // GET: /emailCart/
        [Authorize(Roles = "Photographer")]
        public ViewResult Index()
        {
            return View(repo.getAllEmailItems());
        }


        //**********************
        //Email
        //**********************
        [Authorize(Roles = "Photographer")]
        public ActionResult Email(string result = "")
        {

            ViewBag.result = result;
            return View();
        }


        //**********************
        //Send Email
        //**********************
        [Authorize(Roles = "Photographer")]
        [HttpGet]
        public ActionResult SendEmail()
        {
            return PartialView();
        }



        //**********************
        //Send Email
        //**********************
        [Authorize(Roles = "Photographer")]
        [HttpPost]
        public ActionResult SendEmail(email newEmail)
        {
            List<EmailCart> allPhotoShoots = repo.getAllEmailItems();
            if (ModelState.IsValid)
            {
                List<EmailCart> clearList = new List<EmailCart>();
                string to = newEmail.to;
                string from = newEmail.from;
                MailMessage message = new MailMessage(from, to);
                message.Subject = newEmail.subject;
                message.IsBodyHtml = true;
                message.Body = newEmail.message;
                foreach (var shoots in allPhotoShoots)
                {
                    if (shoots.netId == User.Identity.Name)
                    {
                        message.Body = message.Body + "<br><br>  <a href=\"photo3.byu.edu" + shoots.link + ">" + shoots.photoShootName + "</a>";
                        clearList.Add(shoots);
                    }
                }
                SmtpClient client = new SmtpClient("gateway.byu.edu");
                try
                {
                    client.Send(message);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Exception caught in CreateMessageWithAttachment(): {0}",
                       ex.ToString());
                }
                repo.removeAllEmailItems(clearList);
            }

            return RedirectToAction("Email", new { result = "Email has been sent." });
        }



        //**********************
        //DeleteAll
        //**********************
        [Authorize(Roles = "Photographer")]
        public ActionResult deleteAll()
        {
            List<EmailCart> clearList = new List<EmailCart>();
            foreach (var shoot in repo.getAllEmailItems())
            {
                if (shoot.netId == User.Identity.Name)
                {
                    clearList.Add(shoot);
                }
            }
            repo.removeAllEmailItems(clearList);
          return RedirectToAction("Email", new { result = "Photo shoots have been cleared." });
        }


        //**********************
        //List of shoots added
        //**********************
        [Authorize(Roles = "Photographer")]
        public ActionResult ListOfShootsAdded()
        {
            

            ViewBag.Url =  Request.Url.AbsoluteUri;
            List<EmailCart> emailCart = new List<EmailCart>();
            foreach (var email in repo.getAllEmailItems())
            {
                if (email.netId == User.Identity.Name)
                {
                    emailCart.Add(email);
                }
            }
            return PartialView(emailCart.ToList());
        }


        //**********************
        //Delete
        //**********************
        [Authorize(Roles = "Photographer")]
        public ActionResult Delete(int id, string url)
        { 
           //The URl attribute doesnt always return the correct value this needs to be fixed.
            EmailCart emailcart = repo.getEmailItem(id);
            repo.removeEmailItem(emailcart);
            return RedirectToAction("Index","Home");
        }

        protected override void Dispose(bool disposing)
        {
            repo.Dispose();
        }
    }
}

MvcPhoto2/Controllers/folderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcPhoto2.Models;
using MvcPhoto2.Models.Folders;
using MvcPhoto2.Models.ViewModels;


namespace MvcPhoto2.Controllers
{ 
    public class folderController : Controller
    {
        public JsonResult getJson()
        {
            Photo2repo repo = new Photo2repo();           
            List<foldersJson> allCategories = repo.GetAll();
            return Json(allCategories, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult displayfolder()
        {
            return PartialView();
        }

    }
}

MvcPhoto2/Views/Shared/_Footer.cshtml
<footer>
    
    <div id="footer-bottom">
    <p>
            <a href="http://photo.byu.edu/">BYU Photo Blog</a>
            <a href="http://byuphoto.photoshelter.com/">Photo Store</a>
            </p>
        <p>
            <a href="http://home.byu.edu/home/copyright">Copyright&#169; 2011, All Rights Reserved</a></p>
    </div>
</footer>

MvcPhoto2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title</title>
    
	<link href="@Url.Content("~/Content/template/css/style.css")" rel="stylesheet" type="text/css" />
    <link href="../../Content/Photo2style.css" rel="stylesheet" type="text/css" />
    <script src="/Scripts/jquery-1.8.0.js" type="text/javascript"></script>
	<script src="@Url.Content("~/Content/template/js/libs/modernizr-2.0-basic.min.js")"></script>
	<script>webRoot = "@Url.Content("~/Content/")";</script>
    <!--<script src="../../Scripts/jquery-1.5.1.min.js" type="text/javascript"></script>-->
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
    <script src="../../Scripts/jCarousel.js" type="text/javascript"></script>
    
    








</head>

<body>
	<header id="main-header">
		
           
		<div id="header-top" class="wrapper" style="height:50px;">
			<div id="logo" style="margin:6px 0 0 -18px;">
				<a href="http://www.byu.edu/" class="byu"><img src="@Url.Content("~/Content/template/img/byu-logo.gif")" alt="BYU Logo" /></a>
                
			</div>
            <a href="@Url.Action("Index", "Home")" id="site-name-offical">University Photographers</a>
            @if (User.IsInRole("Photographer"))
            {
			<a href="/Account/Logoff" class="button_Logoff">Logoff</a>
                   
            }
            else
            {
                <a href="/Account/Logon" class="button_Logoff">logon</a>
            }
            </div>
	</header>

	<div id="content" class="wrapper">
        <div class="clearfix">
       
            <div id="PhotoControls">
                    <div >
                    <p>Welcome </p>@Html.Action("GetNetId", "User")
                    
                    </div>
                    <h3>Search</h3>
                
				@using (Html.BeginForm("Search", "PhotoSearch"))
    {   
				
				    <!-- ENTER YOUR SEARCH URL under action -->
                    
                         
                            
                 <div id="search-box">                
                     <div id="search-box">
					    <input type="text" name="searchTerm" id="search" placeholder="Search Photo Shoots" />
					    <input type="image" src="@Url.Content("~/Content/template/img/search-button.png")" alt="Search" id="search-button1"/><br />
                     </div>
                     <!--<input id="photoFormBoxes" type="checkbox" name="checkbox" /><span> View photos only</span> -->
                 </div> 
                <br /><br />
                    <input id="photoFormBoxes" type="checkbox" name="checkbox" /><span> View photos only</span> <br />
         @*@Html.ActionLink("(Advanced Search)", "AdvancedSearch", "PhotoSearch", new { id="photoFormBoxes" })*@
                    	   
    
    }
                    <div id="ControlsList" >
                    @if (User.IsInRole("Admin"))
                        {
                            <h3>Admin Tools</h3>
                            <ul id="PhotoList">
                            <!--<li>@Html.ActionLink("Drop Box", "index", "dropBoxPhoto")</li>-->
                            <li>@Html.ActionLink("Manage Users", "Index", "User")</li>
                            </ul>
                        }
                    </div>
                <div id="ControlsList">
                    <h3>Photo Shoots</h3>
                    <div ><h5>@*@Html.ActionLink("(sync folders)", "index", "FolderStructure")*@</h5></div>
                    <div style="width:150px;">@Html.Action("displayfolder", "folder")</div>
                </div>
                <div id="ControlsList" >
                <h3>Selected Photo Shoots</h3>
                    <ul id="PhotoList">
                    <li>@Html.ActionLink("(Send Email)", "Email", "emailCart")</li>
                       @Html.Action("ListOfShootsAdded", "emailCart", null)
                      
                    </ul>
                    </div>
            </div>
       
            <div style="float:left; margin-left:40px; margin-top:40px;width:600px;">
                <!--<div style="text-align:center"><h1>University Photographers</h1></div>-->
		        @RenderBody()
            </div>
        </div>
	</div>

	@Html.Partial("_Footer")
	
	<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>-->
	<script>	    !window.jQuery && document.write(unescape('%3Cscript src="@Url.Content("~/Content/template/js/libs/jquery.min.js")"%3E%3C/script%3E'))</script>
	<script src="@Url.Content("~/Content/template/js/script.js")"></script>
  
  
</body>
</html>

MvcPhoto2/Views/Shared/_PrimaryNav.cshtml

<nav id="primary-nav" class="no-js">
	<ul>
		<li><a href="">All Photos</a></li>
		<!--<li> <a href="">Departments</a>
			<div class="sub">
				<ul class="links"> 
                  @Html.Action("primaryNav", "Navigation", new {id = 1})  
				</ul>
			</div>
		</li>
        <li> <a href="">Men's Athletics</a>
			<div class="sub">
				<ul class="links"> 
                   @Html.Action("primaryNav", "Navigation", new {id = 2}) 
			    </ul>
			</div>
		</li>
        <li> <a href="">Women's Athletics</a>
			<div class="sub">
				<ul class="links"> 
                   @Html.Action("primaryNav", "Navigation", new {id = 3}) 
			    </ul>
			</div>
		</li>
        <li> <a href="">Staff</a>
			<div class="sub">
				<ul class="links">
                    @Html.Action("primaryNav", "Navigation", new {id = 4})
				</ul>
			</div>
         </li>
        @Html.Action("Navigation", "Nav")-->
		
		<li><a href="">Drop Box</a></li>
        <li><a href="">Search</a></li>
	</ul>
</nav>

MvcPhoto2/Views/Shared/_SecondaryNav.cshtml
<nav id="secondary-nav" class="no-js">
	<ul>
		<!--<li>@Html.ActionLink("Category Manager", "index", "Navigation")
		</li>
		<li><a href="#">Photo Review</a>
			<ul class="sub">
			<li>@Html.ActionLink("Photo add", "PhotoSubmit", "Home")</li>
			<li>@Html.ActionLink("Photo View", "PhotoView", "Home")</li>
			</ul>
		</li>-->
		<li><a href="#">SecMenu3</a>
			<ul class="sub">
			<li><a href="">Link 1</a></li>
			<li><a href="">Link 2</a></li>
			<li><a href="">Link 3</a></li>
			<li><a href="">Link 4</a></li></ul>
		</li>
	</ul>
</nav>